//! Compact, renderer-neutral draw buffers derived from a viewport snapshot.
//!
//! This is the next boundary toward a visible renderer: it expands polygon
//! faces into triangle indices, extracts unique mesh edges, and flattens hair
//! guides into line-segment endpoints. It deliberately does not create a GPU
//! device, camera, shaders, or platform UI.

use crate::{ObjectId, ViewportSceneSnapshot};
use std::collections::BTreeSet;

/// Indexed surface and wireframe buffers for one mesh object.
#[derive(Debug, Clone, PartialEq)]
pub struct ViewportMeshDrawData {
    pub object_id: ObjectId,
    pub name: String,
    /// World-space positions shared by surface and edge buffers.
    pub positions: Vec<[f32; 3]>,
    /// Triangle-list indices generated by dominant-axis ear clipping.
    pub triangle_indices: Vec<u32>,
    /// Unique undirected edge pairs, suitable for a line-list draw call.
    pub edge_indices: Vec<u32>,
    pub is_parametric: bool,
}

/// One hair object's line-list data, retaining its authored color and identity.
#[derive(Debug, Clone, PartialEq)]
pub struct ViewportHairDrawData {
    pub object_id: ObjectId,
    pub name: String,
    pub color: [f32; 4],
    /// Consecutive endpoint pairs; each pair represents one guide segment.
    pub line_positions: Vec<[f32; 3]>,
}

/// A complete CPU-side draw packet for a renderer to upload or consume.
#[derive(Debug, Clone, PartialEq)]
pub struct ViewportDrawData {
    pub active_object: Option<ObjectId>,
    pub meshes: Vec<ViewportMeshDrawData>,
    pub hair: Vec<ViewportHairDrawData>,
}

impl ViewportSceneSnapshot {
    /// Builds indexed surface/wireframe buffers and hair line lists.
    ///
    /// Concave polygons are triangulated with dominant-axis ear clipping.
    /// Invalid or degenerate polygons contribute wireframe edges but no surface
    /// triangles; this keeps malformed geometry from emitting invalid indices.
    pub fn draw_data(&self) -> ViewportDrawData {
        let meshes = self
            .meshes
            .iter()
            .map(|mesh| {
                let mut triangle_indices = Vec::new();
                let mut unique_edges = BTreeSet::new();

                for polygon in &mesh.polygons {
                    if polygon.len() < 2 {
                        continue;
                    }
                    for index in 0..polygon.len() {
                        let a = polygon[index];
                        let b = polygon[(index + 1) % polygon.len()];
                        unique_edges.insert(if a <= b { (a, b) } else { (b, a) });
                    }
                    triangle_indices.extend(triangulate_polygon(&mesh.positions, polygon));
                }

                let edge_indices = unique_edges.into_iter().flat_map(|(a, b)| [a, b]).collect();

                ViewportMeshDrawData {
                    object_id: mesh.id,
                    name: mesh.name.clone(),
                    positions: mesh.positions.clone(),
                    triangle_indices,
                    edge_indices,
                    is_parametric: mesh.is_parametric,
                }
            })
            .collect();

        let hair = self
            .hair
            .iter()
            .map(|object| {
                let mut line_positions = Vec::new();
                for guide in &object.guides {
                    for segment in guide.windows(2) {
                        line_positions.extend_from_slice(&[segment[0], segment[1]]);
                    }
                }
                ViewportHairDrawData {
                    object_id: object.object_id,
                    name: object.name.clone(),
                    color: object.color,
                    line_positions,
                }
            })
            .collect();

        ViewportDrawData {
            active_object: self.active_object,
            meshes,
            hair,
        }
    }
}

/// Triangulates a simple planar polygon using ear clipping after projection
/// onto the plane's dominant axis. Returns an empty list for malformed,
/// self-degenerate, or non-finite polygons rather than generating bad indices.
fn triangulate_polygon(positions: &[[f32; 3]], polygon: &[u32]) -> Vec<u32> {
    if polygon.len() < 3
        || polygon
            .iter()
            .any(|index| (*index as usize) >= positions.len())
    {
        return Vec::new();
    }
    let points: Vec<[f32; 3]> = polygon
        .iter()
        .map(|index| positions[*index as usize])
        .collect();
    if points.iter().flatten().any(|value| !value.is_finite()) {
        return Vec::new();
    }

    let mut normal = [0.0_f64; 3];
    for index in 0..points.len() {
        let current = points[index];
        let next = points[(index + 1) % points.len()];
        normal[0] += (current[1] as f64 - next[1] as f64) * (current[2] as f64 + next[2] as f64);
        normal[1] += (current[2] as f64 - next[2] as f64) * (current[0] as f64 + next[0] as f64);
        normal[2] += (current[0] as f64 - next[0] as f64) * (current[1] as f64 + next[1] as f64);
    }
    let axis = (0..3)
        .max_by(|a, b| normal[*a].abs().total_cmp(&normal[*b].abs()))
        .unwrap();
    if normal[axis].abs() <= 1.0e-12 {
        return Vec::new();
    }

    let projected: Vec<[f64; 2]> = points
        .iter()
        .map(|point| match axis {
            0 => [point[1] as f64, point[2] as f64],
            1 => [point[0] as f64, point[2] as f64],
            _ => [point[0] as f64, point[1] as f64],
        })
        .collect();

    let mut remaining: Vec<usize> = (0..polygon.len()).collect();
    let area = signed_area(&projected, &remaining);
    if area.abs() <= 1.0e-12 {
        return Vec::new();
    }
    let orientation = area.signum();

    // Drop consecutive duplicate and collinear corners from the triangulation
    // ring. The original polygon remains intact in the wireframe buffer.
    let mut changed = true;
    while changed && remaining.len() >= 3 {
        changed = false;
        for i in 0..remaining.len() {
            let previous = remaining[(i + remaining.len() - 1) % remaining.len()];
            let current = remaining[i];
            let next = remaining[(i + 1) % remaining.len()];
            let a = projected[previous];
            let b = projected[current];
            let c = projected[next];
            if distance_squared(a, b) <= 1.0e-24
                || cross_2d(a, b, c).abs() <= 1.0e-12 && point_between(a, b, c)
            {
                remaining.remove(i);
                changed = true;
                break;
            }
        }
    }
    if remaining.len() < 3 {
        return Vec::new();
    }

    let mut triangles = Vec::with_capacity((remaining.len() - 2) * 3);
    let mut attempts = 0;
    while remaining.len() > 3 && attempts < polygon.len() * polygon.len() {
        let mut clipped = false;
        for i in 0..remaining.len() {
            let previous = remaining[(i + remaining.len() - 1) % remaining.len()];
            let current = remaining[i];
            let next = remaining[(i + 1) % remaining.len()];
            let a = projected[previous];
            let b = projected[current];
            let c = projected[next];
            if cross_2d(a, b, c) * orientation <= 1.0e-12 {
                continue;
            }
            let contains_point = remaining.iter().copied().any(|candidate| {
                candidate != previous
                    && candidate != current
                    && candidate != next
                    && point_in_triangle(projected[candidate], a, b, c, orientation)
            });
            if contains_point {
                continue;
            }
            triangles.extend_from_slice(&[polygon[previous], polygon[current], polygon[next]]);
            remaining.remove(i);
            clipped = true;
            break;
        }
        if !clipped {
            return Vec::new();
        }
        attempts += 1;
    }

    if remaining.len() == 3 {
        triangles.extend_from_slice(&[
            polygon[remaining[0]],
            polygon[remaining[1]],
            polygon[remaining[2]],
        ]);
    }
    triangles
}

fn signed_area(points: &[[f64; 2]], indices: &[usize]) -> f64 {
    let mut area = 0.0;
    for i in 0..indices.len() {
        let a = points[indices[i]];
        let b = points[indices[(i + 1) % indices.len()]];
        area += a[0] * b[1] - b[0] * a[1];
    }
    area * 0.5
}

fn cross_2d(a: [f64; 2], b: [f64; 2], c: [f64; 2]) -> f64 {
    (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])
}

fn distance_squared(a: [f64; 2], b: [f64; 2]) -> f64 {
    (a[0] - b[0]).powi(2) + (a[1] - b[1]).powi(2)
}

fn point_between(a: [f64; 2], b: [f64; 2], c: [f64; 2]) -> bool {
    (b[0] - a[0]) * (b[0] - c[0]) + (b[1] - a[1]) * (b[1] - c[1]) <= 1.0e-12
}

fn point_in_triangle(
    point: [f64; 2],
    a: [f64; 2],
    b: [f64; 2],
    c: [f64; 2],
    orientation: f64,
) -> bool {
    cross_2d(a, b, point) * orientation >= -1.0e-12
        && cross_2d(b, c, point) * orientation >= -1.0e-12
        && cross_2d(c, a, point) * orientation >= -1.0e-12
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{HairPreset, HairSettings, PrimitiveKind, Scene};

    #[test]
    fn concave_polygon_ear_clipping_preserves_polygon_area() {
        let positions = vec![
            [0.0, 0.0, 0.0],
            [2.0, 0.0, 0.0],
            [2.0, 2.0, 0.0],
            [1.0, 1.0, 0.0],
            [0.0, 2.0, 0.0],
        ];
        let polygon = vec![0, 1, 2, 3, 4];
        let triangles = triangulate_polygon(&positions, &polygon);
        assert_eq!(triangles.len(), 9);

        let triangle_area: f32 = triangles
            .chunks_exact(3)
            .map(|triangle| {
                let a = positions[triangle[0] as usize];
                let b = positions[triangle[1] as usize];
                let c = positions[triangle[2] as usize];
                ((b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0])).abs() * 0.5
            })
            .sum();
        assert!((triangle_area - 3.0).abs() < 1.0e-5);
    }

    #[test]
    fn triangulation_rejects_invalid_indices_and_degenerate_polygons() {
        assert!(triangulate_polygon(&[[0.0, 0.0, 0.0]], &[0, 1, 0]).is_empty());
        let line = [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [2.0, 0.0, 0.0]];
        assert!(triangulate_polygon(&line, &[0, 1, 2]).is_empty());
    }

    #[test]
    fn cube_draw_data_has_triangle_and_unique_edge_buffers() {
        let mut scene = Scene::new();
        let cube = scene
            .add_primitive("Cube", PrimitiveKind::Cube { size: 1.0 })
            .unwrap();

        let draw = scene.viewport_snapshot().unwrap().draw_data();

        assert_eq!(draw.active_object, Some(cube));
        assert_eq!(draw.meshes.len(), 1);
        let mesh = &draw.meshes[0];
        assert_eq!(mesh.positions.len(), 8);
        assert_eq!(mesh.triangle_indices.len(), 36);
        assert_eq!(mesh.edge_indices.len(), 24);
        assert!(mesh
            .triangle_indices
            .iter()
            .all(|index| (*index as usize) < mesh.positions.len()));
        assert!(mesh
            .edge_indices
            .iter()
            .all(|index| (*index as usize) < mesh.positions.len()));
    }

    #[test]
    fn hair_guides_become_line_segments_without_losing_color_or_identity() {
        let mut scene = Scene::new();
        let mut source_mesh = crate::Mesh::new();
        let a = source_mesh.add_vertex([0.0, 0.0, 0.0]);
        let b = source_mesh.add_vertex([1.0, 0.0, 0.0]);
        let c = source_mesh.add_vertex([0.0, 0.0, 1.0]);
        let face = source_mesh.add_face(&[a, c, b]).unwrap();
        let source = scene.add_mesh("Scalp", source_mesh).unwrap();
        let settings = HairSettings {
            amount: 3,
            ..HairSettings::short_hair()
        };
        let hair_id = scene
            .add_hair_object("Hair", source, &[face], HairPreset::ShortHair, settings)
            .unwrap();

        let draw = scene.viewport_snapshot().unwrap().draw_data();

        assert_eq!(draw.hair.len(), 1);
        let hair = &draw.hair[0];
        assert_eq!(hair.object_id, hair_id);
        assert_eq!(hair.name, "Hair");
        assert_eq!(hair.color, settings.color);
        // Each guide currently has six points, hence five line segments.
        assert_eq!(hair.line_positions.len(), 3 * 5 * 2);
    }

    #[test]
    fn shared_polygon_edges_are_emitted_only_once() {
        let mut scene = Scene::new();
        let cube = scene
            .add_primitive("Cube", PrimitiveKind::Cube { size: 1.0 })
            .unwrap();
        let draw = scene.viewport_snapshot().unwrap().draw_data();
        let mesh = draw
            .meshes
            .iter()
            .find(|mesh| mesh.object_id == cube)
            .unwrap();

        let edge_pairs: Vec<_> = mesh.edge_indices.chunks_exact(2).collect();
        assert_eq!(edge_pairs.len(), 12);
        let mut sorted = edge_pairs
            .iter()
            .map(|edge| (edge[0].min(edge[1]), edge[0].max(edge[1])))
            .collect::<Vec<_>>();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(sorted.len(), edge_pairs.len());
    }
}
